### ISSUE TITLE
signal.h to handle writes to closed connections

### ISSUE THREAD

**Issue by CanadianJeff** [yorickdewid/Chat-Server#3]
For a multithreaded program, the correct action is usually to ignore the SIGPIPE signal, so that writing to a closed socket will not terminate the program.

```
<[SERVER STARTED]>
[New Thread 0x7ffff782a700 (LWP 9533)]

Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7ffff782a700 (LWP 9533)]
0x00007ffff7bcd7cd in write () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff7bcd7cd in write () from /lib64/libpthread.so.0
#1  0x0000000000401234 in send_message_all ()
#2  0x0000000000401abd in handle_client ()
#3  0x00007ffff7bc6aa1 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff7913bcd in clone () from /lib64/libc.so.6
(gdb)
```

**Comment by yorickdewid** [comment]
Even though this is an 4 year old project and is far from perfect, I took 2 minutes to squeezed in a oneliner that should ignore pipe signals.

**Comment by CanadianJeff** [comment]
this works great thanks
